title: Colmeia UDESC
logo: /assets/img/logo.png
description: Site oficial do grupo de extensão Socialização em Software Livre e Hardware Livre - Colmeia
google_analytics:
theme: jekyll-theme-minimal

social_links:
  youtube_channel: UC51KrWL94AfGxI_4l_E7uzA
  github:  colmeiaUDESC
  facebook: colmeiaudesc
  instagram: colmeiaudesc